# Generated by Django 4.2.1 on 2023-05-24 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("GuideForum", "0002_alter_tag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_topics", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
