# Generated by Django 4.2.1 on 2023-05-23 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("GuideForum", "0003_topic_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="owner",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
